<a href="https://colab.research.google.com/github/annaannaR/NOTEBOOKS-FROM-SCHOOL/blob/main/final_project/projekt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import csv
from io import StringIO

# make sure that plots are visible in this notebook
%matplotlib inline

In [ ]:
sheets = pd.read_excel("Vivino-export.xlsx", engine="openpyxl", sheet_name=None)

dfs = []
bad_lines_log = []

for sheet_name, df_raw in sheets.items():
    if df_raw.empty:
        continue

    text = "\n".join(df_raw.iloc[:, 0].astype(str).tolist())

    try:
        df_part = pd.read_csv(
            StringIO(text),
            sep=",",
            engine="python",
            quoting=csv.QUOTE_MINIMAL,
            on_bad_lines="skip"
        )
    except Exception as e:
        bad_lines_log.append((sheet_name, f"FAILED ENTIRE SHEET: {e}"))
        continue

    df_part.columns = ["name", "country", "region", "rating", "rating_count", "price"]
    df_part["sheet"] = sheet_name

    dfs.append(df_part)

df = pd.concat(dfs, ignore_index=True)

In [ ]:
df

,name,country,region,rating,rating_count,price,sheet
0,Caiarossa Aria di Caiarossa 2015,"('Itali√´',)","('Toscane',)",4.2,506,28.047878,Italie
1,Martin Tesch Unplugged Riesling 2019,"('Duitsland',)","('Nahe',)",3.7,129,10.287832,Italie
2,Azienda Agricola I Luoghi Podere Ritorti Bolgh...,"('Itali√´',)","('Bolgheri Superiore',)",4.2,63,28.697636,Italie
3,Caiarossa Aria di Caiarossa 2015,"('Itali√´',)","('Toscane',)",4.2,504,28.088608,Uruguay
4,Martin Tesch Unplugged Riesling 2019,"('Duitsland',)","('Nahe',)",3.7,129,10.302771,Uruguay
...,...,...,...,...,...,...,...
409737,Cremaschi Furlotti Cabernet Sauvignon Reserva ...,"('Chili',)","('Valle del Loncomilla',)",3.4,235,11.577249,New Zealand
409738,Vergelegen Sauvignon Blanc 2019,"('Zuid-Afrika',)","('Stellenbosch',)",3.6,145,21.419927,New Zealand
409739,Vergelegen Cabernet Sauvignon - Merlot 2017,"('Zuid-Afrika',)","('Stellenbosch',)",4.0,145,21.419927,New Zealand
409740,Clearwater Cove Sauvignon Blanc Ros√© 2020,"('New Zealand',)","('Marlborough',)",3.9,111,13.029447,New Zealand
409741,Clearwater Cove Pinot Grigio (Gris) 2020,"('New Zealand',)","('Marlborough',)",4.0,79,13.029447,New Zealand

In [ ]:
df.country.value_counts()

country
('Frankrijk',)              192868
('Itali√´',)                 77366
('Spanje',)                  35600
('Australi√´',)              31138
('Portugal',)                15415
('Verenigde Staten',)        13154
('Argentini√´',)             12099
('Chili',)                   11500
('Duitsland',)                4718
('New Zealand',)              4681
('Zuid-Afrika',)              3064
('Oostenrijk',)               2786
('Brazili√´',)                1452
('Libanon',)                  1178
('Uruguay',)                   604
('Griekenland',)               515
('Canada',)                    480
('Armeni√´',)                  384
('Hongarije',)                 258
('Verenigd Koninkrijk',)       142
('Moldavi√´',)                 114
('Georgi√´',)                   48
('Mexico',)                     34
('Luxembourg',)                 34
('Serbia',)                     24
('Isra√´l',)                    21
('Marokko',)                    12
('Slowakije',)                  12
('Roemeni√´',)                  12
('Kroati√´',)                   12
('Noord-Macedoni√´',)            7
('Syri√´',)                      3
('Rusland',)                     3
('Montenegro',)                  2
('Bulgarije',)                   2
Name: count, dtype: int64

In [ ]:
df.country = df.country.astype(str).str.replace(r"[()'√´,]","", regex=True)
df.region = df.region.astype(str).str.replace(r"[()'√´,]","", regex=True)
df.country = df.country.astype(str).str.replace(r"[()'√´,]","", regex=True)
df

,name,country,region,rating,rating_count,price,sheet
0,Caiarossa Aria di Caiarossa 2015,Itali,Toscane,4.2,506,28.047878,Italie
1,Martin Tesch Unplugged Riesling 2019,Duitsland,Nahe,3.7,129,10.287832,Italie
2,Azienda Agricola I Luoghi Podere Ritorti Bolgh...,Itali,Bolgheri Superiore,4.2,63,28.697636,Italie
3,Caiarossa Aria di Caiarossa 2015,Itali,Toscane,4.2,504,28.088608,Uruguay
4,Martin Tesch Unplugged Riesling 2019,Duitsland,Nahe,3.7,129,10.302771,Uruguay
...,...,...,...,...,...,...,...
409737,Cremaschi Furlotti Cabernet Sauvignon Reserva ...,Chili,Valle del Loncomilla,3.4,235,11.577249,New Zealand
409738,Vergelegen Sauvignon Blanc 2019,Zuid-Afrika,Stellenbosch,3.6,145,21.419927,New Zealand
409739,Vergelegen Cabernet Sauvignon - Merlot 2017,Zuid-Afrika,Stellenbosch,4.0,145,21.419927,New Zealand
409740,Clearwater Cove Sauvignon Blanc Ros√© 2020,New Zealand,Marlborough,3.9,111,13.029447,New Zealand
409741,Clearwater Cove Pinot Grigio (Gris) 2020,New Zealand,Marlborough,4.0,79,13.029447,New Zealand

In [ ]:
df.country.value_counts()

country
Frankrijk              192868
Itali                   77366
Spanje                  35600
Australi                31138
Portugal                15415
Verenigde Staten        13154
Argentini               12099
Chili                   11500
Duitsland                4718
New Zealand              4681
Zuid-Afrika              3064
Oostenrijk               2786
Brazili                  1452
Libanon                  1178
Uruguay                   604
Griekenland               515
Canada                    480
Armeni                    384
Hongarije                 258
Verenigd Koninkrijk       142
Moldavi                   114
Georgi                     48
Mexico                     34
Luxembourg                 34
Serbia                     24
Isral                      21
Marokko                    12
Slowakije                  12
Roemeni                    12
Kroati                     12
Noord-Macedoni              7
Syri                        3
Rusland                     3
Montenegro                  2
Bulgarije                   2
Name: count, dtype: int64

In [ ]:
df.region.value_counts()

region
Grand cru Saint-âmilion    20878
Champagne                  19529
Pauillac                   15857
Margaux                    13952
Saint-Est®phe              12406
                           ...
New York                       1
Brachetto d‚ÄôAcqui            1
Bourgogne Mousseux             1
Maury                          1
Alsace Grand Cru               1
Name: count, Length: 753, dtype: int64

In [ ]:
df["year"] = df.name.str.extract(r"(\d{4})")
df

,name,country,region,rating,rating_count,price,sheet,year
0,Caiarossa Aria di Caiarossa 2015,Itali,Toscane,4.2,506,28.047878,Italie,2015
1,Martin Tesch Unplugged Riesling 2019,Duitsland,Nahe,3.7,129,10.287832,Italie,2019
2,Azienda Agricola I Luoghi Podere Ritorti Bolgh...,Itali,Bolgheri Superiore,4.2,63,28.697636,Italie,2018
3,Caiarossa Aria di Caiarossa 2015,Itali,Toscane,4.2,504,28.088608,Uruguay,2015
4,Martin Tesch Unplugged Riesling 2019,Duitsland,Nahe,3.7,129,10.302771,Uruguay,2019
...,...,...,...,...,...,...,...,...
409737,Cremaschi Furlotti Cabernet Sauvignon Reserva ...,Chili,Valle del Loncomilla,3.4,235,11.577249,New Zealand,2017
409738,Vergelegen Sauvignon Blanc 2019,Zuid-Afrika,Stellenbosch,3.6,145,21.419927,New Zealand,2019
409739,Vergelegen Cabernet Sauvignon - Merlot 2017,Zuid-Afrika,Stellenbosch,4.0,145,21.419927,New Zealand,2017
409740,Clearwater Cove Sauvignon Blanc Ros√© 2020,New Zealand,Marlborough,3.9,111,13.029447,New Zealand,2020
409741,Clearwater Cove Pinot Grigio (Gris) 2020,New Zealand,Marlborough,4.0,79,13.029447,New Zealand,2020

In [ ]:
df.name = df.name.replace(r"\s*\d{4}$", "", regex=True)
df

,name,country,region,rating,rating_count,price,sheet,year
0,Caiarossa Aria di Caiarossa,Itali,Toscane,4.2,506,28.047878,Italie,2015
1,Martin Tesch Unplugged Riesling,Duitsland,Nahe,3.7,129,10.287832,Italie,2019
2,Azienda Agricola I Luoghi Podere Ritorti Bolgh...,Itali,Bolgheri Superiore,4.2,63,28.697636,Italie,2018
3,Caiarossa Aria di Caiarossa,Itali,Toscane,4.2,504,28.088608,Uruguay,2015
4,Martin Tesch Unplugged Riesling,Duitsland,Nahe,3.7,129,10.302771,Uruguay,2019
...,...,...,...,...,...,...,...,...
409737,Cremaschi Furlotti Cabernet Sauvignon Reserva,Chili,Valle del Loncomilla,3.4,235,11.577249,New Zealand,2017
409738,Vergelegen Sauvignon Blanc,Zuid-Afrika,Stellenbosch,3.6,145,21.419927,New Zealand,2019
409739,Vergelegen Cabernet Sauvignon - Merlot,Zuid-Afrika,Stellenbosch,4.0,145,21.419927,New Zealand,2017
409740,Clearwater Cove Sauvignon Blanc Ros√©,New Zealand,Marlborough,3.9,111,13.029447,New Zealand,2020
409741,Clearwater Cove Pinot Grigio (Gris),New Zealand,Marlborough,4.0,79,13.029447,New Zealand,2020